voting-app:
  build: ./voting-app/.
  volumes:
    - ./voting-app:/app
  ports:
    - "5000:80"

redis:
  image: hypriot/rpi-redis
  ports: ["6379"]

worker:
  build: ./worker/.

db:
  image: zsoltm/postgresql-armhf
  volumes:
    - "myvolume:/var/lib/postgresql/data"

result-app:
  build: ./result-app/.
  volumes:
    - ./result-app:/app
  ports:
    - "5001:80"
